### ISSUE TITLE
iOS15.0 cofishhook.c crash 

### ISSUE THREAD

**Issue by tzwgod** [alibaba/coobjc#112]
### Environment Details

* coobjc version: 1.2.0
* iOS version: 15.0
* Xcode version: 12.5.1, 13.0
* Other informations: 

![image](https://user-images.githubusercontent.com/13271517/134444808-1c4c8be6-72ac-4294-b764-60f608b3cde8.png)

![image](https://user-images.githubusercontent.com/13271517/134444523-be156e80-003a-4d9f-8900-1e2e44279c58.png)

![image](https://user-images.githubusercontent.com/13271517/134446350-6aad1452-d53a-4c63-8306-439f69768a5b.png)

**Comment by yunjinghui123** [comment]
The same question，iOS 15.0 crash

**Comment by nasio-limbo** [comment]
[App Name] was compiled with optimization - stepping may behave oddly; variables may not be available.

**Comment by chanshiguan** [comment]
The same question，iOS 15.0 crash

**Comment by zhengshengxi** [comment]
iOS15 崩溃
位于 indirect_symbol_bindings[i] = cur->rebindings[j].replacement;

**Comment by yunjinghui123** [comment]
Does anyone solve it, many places in the project use this framework, not good replacement.

**Comment by NianJi** [comment]
Use: cf99ab4aae0ff73731bbf765d2bd08645684c733

**Comment by tzwgod** [comment]
@NianJi  Resolved, thank you

**Comment by zhengshengxi** [comment]
> Use this commit: [cf99ab4](https://github.com/alibaba/coobjc/commit/cf99ab4aae0ff73731bbf765d2bd08645684c733)
> 
> If problem resolved, I will publish a new tag to cocoapods

请问什么时候会推送到cocoapods
