### ISSUE TITLE
iOS15.0 cofishhook crash.

### ISSUE THREAD

**Issue by CodeKevin** [alibaba/coobjc#113]
### Context and Description

cofishhook crash when open our project.

### Environment Details

* coobjc version:1.2.0
* iOS version:15.0
* Xcode version:13.0

**Comment by yunjinghui123** [comment]
#112

**Comment by chaselen** [comment]
修复了麻烦更新一下CocoaPods吧。。

**Comment by CodeKevin** [comment]
#112
