### ISSUE TITLE
【崩溃】调用co_launch{ } 必现crash

### ISSUE THREAD

**Issue by baoshanzhang** [alibaba/coobjc#117]
### Environment Details

* coobjc version: 1.2.0
* iOS version: 16
* Xcode version:14.1
* Other informations:

### swift 调用co_launch{ } 必定crash
![image](https://user-images.githubusercontent.com/21193117/205267386-95510164-e13c-4792-a47d-9f3320297b2d.png)

**Comment by NianJi** [comment]
这个是依赖的 fishhook 挂了，可以试试自行拷贝最新的fishhook替换一下， 或者干脆注释fishhook 的调用，这里只是在 debug 的时候生效，用于调试时查看堆栈的。
