### ISSUE TITLE
好人做到底，送佛送到西

### ISSUE THREAD

**Issue by Roen-Ro** [alibaba/coobjc#12]
阿里的大牛们，你就好人做到底，送佛送送到西 干脆整一套完整的App框架出来，把网络请求、数据库存储、常用UI控件、各种小工具、各种基础功能都整合到一起，以后我们再开发App的时候就不用自己再东挪西套地搭建了，拿来直接用。
此乃程序员之福、万民之福！

**Comment by myCout** [comment]
哈哈，让大牛们直接开发好的啦。

**Comment by wangergang** [comment]
这样的话, 写代码就是也是程序化的页面了, 那么请问我们会不会失业...

感觉在过几年 , 估计真的会程序化实现了, 慌得很...

**Comment by xiaohange** [comment]
> 阿里的大牛们，你就好人做到底，送佛送送到西 干脆整一套完整的App框架出来，把网络请求、数据库存储、常用UI控件、各种小工具、各种基础功能都整合到一起，以后我们再开发App的时候就不用自己再东挪西套地搭建了，拿来直接用。
> 此乃程序员之福、万民之福！

感觉想太多了~
