### ISSUE TITLE
如何发起多个异步网络请求，像dispatch_group那样

### ISSUE THREAD

**Issue by DouKing** [alibaba/coobjc#19]

**Comment by pengyutang125** [comment]
/**
 batch_await
 
 @param _promiseOrChanArray a NSArray of  COPromise object or COChan object.
 @return return the NSArray of values, if value is nil, the element is NSNull.
 */

**Comment by DouKing** [comment]
![snip20190303_8](https://user-images.githubusercontent.com/6213779/53692388-0d757380-3dca-11e9-9b5e-3f3651b01e4c.png)
![snip20190303_7](https://user-images.githubusercontent.com/6213779/53692389-1108fa80-3dca-11e9-800a-dad453b5737b.png)
你好，这是我测试发现的问题，不知是哪里使用不当
