### ISSUE TITLE
卡死

### ISSUE THREAD

**Issue by liuqingtong** [alibaba/coobjc#2]
Discover项目列表push pop 多次，界面卡死。。

**Comment by pengyutang125** [comment]
能不能麻烦提供一下卡死时候的堆栈，我们自己本地测试并没有界面卡死，有堆栈的话，才好进一步分析一下

**Comment by liuqingtong** [comment]
![img_3571](https://user-images.githubusercontent.com/11865589/53548748-406efb80-3b6d-11e9-964c-627793ceba51.PNG)
![img_3570](https://user-images.githubusercontent.com/11865589/53548751-4238bf00-3b6d-11e9-9357-6b0460b186e9.PNG)
没有log信息，第二张图是切到后台再回来的时候，应该是导航控制器的问题。堆栈我再看看。

**Comment by zhangtibin** [comment]
果然会卡死，这个 demo 使用 MLeaksFinder 检测时，多处内存泄露；
![image](https://user-images.githubusercontent.com/9295805/53552995-93e64700-3b77-11e9-819d-43f8b2f4bc04.png)

**Comment by pengyutang125** [comment]
这里是为了方便，直接从github上用的开源示例做的演示，主要是为了说明协程的使用，所以没有过多关心Demo本身的稳定性和问题

**Comment by zhangtibin** [comment]
做静态代码分析时，也有好几个 Memory error,影响吗？
![image](https://user-images.githubusercontent.com/9295805/53554682-423fbb80-3b7b-11e9-8748-600c41cd4981.png)
