### ISSUE TITLE
COPromise 问题

### ISSUE THREAD

**Issue by yinjiahjk** [alibaba/coobjc#26]
- (COPromise*)downloadImageWithError{
    COPromise *promise = [COPromise promise];
    long total = 0;
    for (int i = 0; i < 100000000; i++) {
        total += i;
    }
    NSError* error = [NSError errorWithDomain:@"wrong" code:20 userInfo:@{@"h":@"yc"}];
    [promise reject:error];
    return promise;
}

co_launch(^{
            id dd = await([self downloadImageWithError]);
            if(co_getError()){
                NSLog(@"33");------>这里进不了！！！！
            }
        });

**Comment by kiss587898** [comment]
写法不对吧，要异步

**Comment by yinjiahjk** [comment]
> 写法不对吧，要异步
你说的对。。。
