### ISSUE TITLE
关于生成器使用的疑问

### ISSUE THREAD

**Issue by ZXLBoaConstrictor** [alibaba/coobjc#28]
![1](https://img-blog.csdnimg.cn/20190305143717743.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NreV9sb25nX2ZseQ==,size_16,color_FFFFFF,t_70)
![2](https://img-blog.csdnimg.cn/20190305143754608.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NreV9sb25nX2ZseQ==,size_16,color_FFFFFF,t_70)
![3](https://img-blog.csdnimg.cn/20190305143847329.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NreV9sb25nX2ZseQ==,size_16,color_FFFFFF,t_70)
如图我在阅读生成器使用的时候，使用测试用例里面的代码看效果，能从代码中看出循环下载10次同样的文件，但是看到我控制台日志输出显示我使用了11次下载。能解释一下吗？

**Comment by NianJi** [comment]
It is a problem.  `yield` should pause the expression behind.  But now, it just executed, `yield` just pause for return value.

**Comment by NianJi** [comment]
Because `co_downloadWithURL:` is directly in the download operation. Using `Promise` could avoid this. It should be that the code sample in Demo is wrong and will be fixed later.

**Comment by ZXLBoaConstrictor** [comment]
在对说明文档阅读中，我有注意到coobjc中比较重要的部分都给出了说明。希望能看到有比较详细的一些场景使用，还有能解决此场景中的问题点。非常感谢！！！
