### ISSUE TITLE
Promise should execute direct.

### ISSUE THREAD

**Issue by NianJi** [alibaba/coobjc#30]
We have a design problem with Promise. If you create COPromise with `promise:(COPromiseConstructor)constructor` method.  COPromise does not execute directly.

It may cause problem like this.
We expect this code can concurrent:
```
// concurrent
id promise1 = getPromise1();
id promise2 = getPromise2();

id result1 = await(promise1);
id result2 = await(promise2);
```

But it's not concurrent, I think Promise should execute direct, instead of execute at first `then`.

If you have any idea, replay.

**Comment by ValiantCat** [comment]
JavaScript promise execute Direct,
IN ECMA6, await a async method, just like promise.

**Comment by JinjunHan** [comment]
目前，可以使用``batch_await()``来并发多个promise，返回的resultArray是按照promise array的顺序返回，可以按以下写法：
```
  NSArray *resultArray = batch_await(@[promise1, promise2, promise3]);

  // do something promise1
  id result1 = resultArray[0];
  
  // do something promise2
  id result2 = resultArray[2];
        
  // do something promise3
  id result3 = resultArray[3];

  // do something in the end
  NSLog(@"tableView reloadData");
```
但是，如果插入或删除中间的某个promise，会导致序号变化，也是不太友好的写法。

可以试着多一个像``batch_await()``的函数，返回值是元组``tuple``
```
  id result1, result2, result3;
  co_unpack(&result1, &result2, &result3) = batch_await(@[promise1, promise2, promise3]);
  // do something promise1
  NSLog(@"%@", result1);
  
  // do something promise2
  NSLog(@"%@", result2);
        
  // do something promise3
  NSLog(@"%@", result3);

  // do something in the end
  NSLog(@"tableView reloadData");
```
这样的写法，可以减少序号出现变化的影响。但是，这也是存在些缺点，当promise数量比较多的时候，代码还是有些臃肿。
还有其他的思路，如：增加类似线程池、await增加block处理，还没想好

**Comment by NianJi** [comment]
fix in: https://github.com/alibaba/coobjc/pull/31
