### ISSUE TITLE
关于coobjcBaseExample中的COActor的使用问题

### ISSUE THREAD

**Issue by binhan198** [alibaba/coobjc#33]
代码中有这样一段，在DataService类中：
```
_networkActor = co_actor_onqueue(_networkQueue, ^(COActorChan *channel) {
            for (COActorMessage *message in channel) {
                NSString *url = [message stringType];
                if (url.length > 0) {
                    message.complete(await([self _getDataWithURL:url]));
                }
                else{
                    message.complete(nil);
                }
            }
        });
```
不知道是否是我理解的问题，每次向这个actor发送消息只有等到_getDataWithURL网络请求方法回调完成之后才能继续下一个请求，这样网络的请求过程是不是不能并发。

**Comment by pengyutang125** [comment]
_networkActor = co_actor_onqueue(_networkQueue, ^(COActorChan *channel) {
            for (COActorMessage *message in channel) {
                NSString *url = [message stringType];
                if (url.length > 0) {
                    co_launch(^{
                            message.complete(await([self _getDataWithURL:url]));
                    });
                }
                else{
                    message.complete(nil);
                }
            }
        });

使用上述方式的嵌套协程，可以解决你说的问题
