### ISSUE TITLE
concurrent await promise bug

### ISSUE THREAD

**Issue by JinjunHan** [alibaba/coobjc#34]
在concurrent await promise test中，在两个``await()``之间插入代码``NSLog()``，就无法继续执行下面的代码。
<img width="862" alt="p1" src="https://user-images.githubusercontent.com/13652851/53868396-f1bfd680-4030-11e9-8edc-638be21dd52d.png">
<img width="773" alt="p2" src="https://user-images.githubusercontent.com/13652851/53868414-f97f7b00-4030-11e9-9164-b9dd9ce93221.png">
<img width="868" alt="p3" src="https://user-images.githubusercontent.com/13652851/53868425-ff755c00-4030-11e9-93d8-785a14489c8d.png">

**Comment by NianJi** [comment]
这个是因为 waitUntil 里面 5秒后就 done()了，单测没机会执行了，改为6就好了。。

**Comment by JinjunHan** [comment]
这么神奇，为啥在await之间插入了其他代码会影响到。只在所有await之后写代码却没影响
