### ISSUE TITLE
为什么没有co_repeat？？

### ISSUE THREAD

**Issue by KoonChaoSo** [alibaba/coobjc#36]
---
name: Issue template
about: Describe this issue template's purpose here.

---

### Context and Description
为什么没有co_repeat？？

### Environment Details

* coobjc version:
* iOS version:
* Xcode version:
* Other informations:

**Comment by NianJi** [comment]
本来有这个接口，但是发现好像没有使用场景，就删了，你可以说说你的场景么？

**Comment by KoonChaoSo** [comment]
我只是想测试一下文章上面 并发n个读取文件的操作来做压测，发现测试结果并不是上面写的，然后分析发现应该是用for {  co_launch {} } 这样写是有问题的，并不能代替co_repeat，所以想看看。

**Comment by NianJi** [comment]
可以试下 for { co_launch_onqueue{} }

**Comment by KoonChaoSo** [comment]
![image](https://user-images.githubusercontent.com/6228912/54005663-4714f880-4195-11e9-948b-6790f2b70c24.png)
![image](https://user-images.githubusercontent.com/6228912/54005738-82afc280-4195-11e9-9c5a-2c1d9d67ae3d.png)

我发现这样写，时间会比我传统线程的时间要长1到2倍，不过的确在循环500个以上，传统线程执行会报错。

**Comment by NianJi** [comment]
我跑了下你的demo，时间是差不多的。 你2个方法不会是同时跑的吧，cpu占用会互相干扰。而且文件大小也有影响。

**Comment by KoonChaoSo** [comment]
是的。我不会同时跑，然后 我的文件大小是 9.9M 哈。测试结果如下哈。iPhoneX，12.1.4
![image](https://user-images.githubusercontent.com/6228912/54007565-6e6fc380-419d-11e9-80f1-98fd052ee4b2.png)

**Comment by NianJi** [comment]
其实这个例子里面没有真正的异步api的使用 initWithContentOfFile: 其实还是同步io，性能是不可能好于线程的, 代码还是在线程里面执行。 协程的理想使用场景是 高并发 + 异步io。 

在客户端上的话，在编程范式上给我们一定的启发： 可以用同步方式写异步代码，便于理解。 还有比如我们可以控制线程数，然后用协程异步调度，来减少线程使用，提升性能。
