### ISSUE TITLE
关于await的一点小疑问

### ISSUE THREAD

**Issue by nannanIT** [alibaba/coobjc#37]
最近在研究了一下coobjc框架，很优秀，学到了很多东西。但是还有一点疑问，希望能交流一下。
    协程可以避免多线程切换带来性能消耗，但是await会等待一个promise，promise还是会在子线程去执行，结果回调到主线程，这个操作算不算线程切换呢？当然多个协程在一个线程中切换肯定是没有压力的。所以我的疑问是await等待一个promise到执行结束回调的过程中，哪些仍然算线程操作，哪些算协程减少的操作，或者说协程带来的收益。谢谢

**Comment by NianJi** [comment]
问题： 算线程切换。

1、所有的协程代码都在线程中执行，真实的代码执行不会优于线程。
2、协程的意义在于异步，如果都是同步代码，没有区别。 协程的意义是用同步的方式访问异步的api, 协程的阻塞不是真阻塞，不会浪费线程去做单纯的等待。 这一点在服务端 协程 + 异步io实现高并发上提现的意义更大。
3、在客户端上，我们探索通过协程帮助我们写更容易理解的异步代码逻辑，而不用一直callback。避免线程中各种同步逻辑锁住线程浪费资源，还有线程安全樱花。

**Comment by nannanIT** [comment]
谢谢您的回复，大概明白了。
