### ISSUE TITLE
在.mm文件中使用编译报错

### ISSUE THREAD

**Issue by Vickeywei** [alibaba/coobjc#46]
Undefined symbols for architecture arm64:
  "co_await(objc_object*)", referenced from:
      ___29-[ViewController viewDidLoad]_block_invoke in ViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
我在.mm文件中使用await会产生上面的错误.在新建的工程中使用也是这样,我想问是否支持objective-c++

**Comment by pengyutang125** [comment]
这是因为coobjc.h的头文件里没有包含extern "c", 我已经提交修复了，你也可以用如下方式避免编译问题：
`extern "c"{
#import <coobjc/coobjc.h>
}`

**Comment by Vickeywei** [comment]
谢谢
