### ISSUE TITLE
cocoapods 上找不到这个库，是还没有上传成功吗？

### ISSUE THREAD

**Issue by ZYiDa** [alibaba/coobjc#5]
[!] Unable to find a specification for `coobjc`

**Comment by pengyutang125** [comment]
已经上传了，cocoapods仓库需要手动更新，不是自动更新的

**Comment by ZYiDa** [comment]
> 已经上传了，cocoapods仓库需要手动更新，不是自动更新的

尴尬  忘记了这个。。。哈哈哈哈哈哈哈哈

**Comment by ValiantCat** [comment]
pod repo update
