### ISSUE TITLE
crash if run co_launch in background thread

### ISSUE THREAD

**Issue by jackieyk** [alibaba/coobjc#60]
---
name: crash if run co_launch in background thread
about: run co_launch in a background thread triggerred by performInBackground method, app crashed

---

### Context and Description
Sample code:

- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    [self performSelectorInBackground:@selector(test) withObject:nil];
}

- (void)test {
    co_launch(^{   //Crashed here. EXC_BAD_ACCESS(code=1, address=0x54)
        NSLog(@"111111");
        NSLog(@"22222");
        NSLog(@"33333");
    });
    NSLog(@"44444");
    NSLog(@"55555");
}

### Environment Details

* coobjc version:1.1.3
* iOS version:iPhoneX simulator
* Xcode version:Xcode 10
* Other informations:

**Comment by NianJi** [comment]
For now, coobjc just support run in a dispatch_queue_t. 

We consider support thread.

**Comment by jackieyk** [comment]
coobjc所在方法（例子中的test）并不知道自己如何被别人调用，是放在一个gcd queue里，还是performSelectorInBackground。 
建议尽快支持一下，否则容易出问题

**Comment by pengyutang125** [comment]
已经针对这种情况进行了支持，在feature分支中，本周会发布到pods仓库
