### ISSUE TITLE
dispatch_semaphore_wait导致GCD假死防护

### ISSUE THREAD

**Issue by wangjufan** [alibaba/coobjc#7]
我们知道GCD的线程池最多有64个线程，如果它们全都在等待信号，
而信号的发送者这时候又分发到全局队列上了，这将导致GCD假死的现象产生。

协程应该有这个能力来解决这个问题。
在dispatch_semaphore_wait或是之前某个时刻做检测，
当需要等待时，让出线程，在有信号发出时，重新分发任务。

各位大神，不知道这个提议是否可行？

**Comment by pengyutang125** [comment]
最合适的方式是不使用信号量

**Comment by wangjufan** [comment]
对对，本身就是为了降低小任务协作中线程的使用问题。

**Comment by xiaohange** [comment]
使用GCD队列解决岂不更好~
