### ISSUE TITLE
自己创建framework 库，使用了coobjc的库

### ISSUE THREAD

**Issue by huangzhentong** [alibaba/coobjc#73]
自己创建framework 库，使用了coobjc的库，打包出来后 
使用framework 会报Undefined symbols for architecture x86_64:
  "_PodKTFindCarSDK_coroutine_begin", referenced from:
      _PodKTFindCarSDK_coroutine_resume_im in KTFindCarSDK(coroutine.o)
  "_PodKTFindCarSDK_coroutine_getcontext", referenced from:
      _PodKTFindCarSDK_coroutine_yield in KTFindCarSDK(coroutine.o)
      _PodKTFindCarSDK_coroutine_resume_im in KTFindCarSDK(coroutine.o)
  "_PodKTFindCarSDK_coroutine_setcontext", referenced from:
      _PodKTFindCarSDK_coroutine_yield in KTFindCarSDK(coroutine.o)
      _PodKTFindCarSDK_coroutine_resume_im in KTFindCarSDK(coroutine.o)
      _coroutine_main in KTFindCarSDK(coroutine.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)的错误

**Comment by pengyutang125** [comment]
还需要依赖cocore这个库

**Comment by huangzhentong** [comment]
添加了cocore库的依赖，打出来的framework 包 到另一个工程还是报一样的错

**Comment by NianJi** [comment]
你的工程为什么会报 `_PodKTFindCarSDK_coroutine_begin` 这样的符号找不到，应该是 `_coroutine_begin`,  所以是不是工程的其他配置有什么问题？

推荐使用 cocoapods 进行依赖
