### ISSUE TITLE
CODispatc.m 的一个问题

### ISSUE THREAD

**Issue by s2mh** [alibaba/coobjc#74]
[dispatch_async_block](https://github.com/alibaba/coobjc/blob/93de4d3311a89514d1853da0e91f01bbbd89a8c0/cocore/CODispatch.m#L124) 和 [dispatch_block](https://github.com/alibaba/coobjc/blob/master/cocore/CODispatch.m#L144) 中 waitUntilDone:NO 有问题：如果 _thread 未启动 runloop，那么 @selector(handleBlock:) 不会被执行。

**Comment by NianJi** [comment]
目前 CODispatch 其实还是不能够支持thread的，推荐使用 dispatch_queue来执行。 关于thread的支持后续会考虑更好的支持。

简单的改为 waitUntilDone:YES， 违背了异步的精深，所以不会采纳。
