### ISSUE TITLE
做静态代码分析时，也有好几个 Memory error,影响吗？

### ISSUE THREAD

**Issue by pengyutang125** [alibaba/coobjc#8]
做静态代码分析时，也有好几个 Memory error,影响吗？
![image](https://user-images.githubusercontent.com/9295805/53554682-423fbb80-3b7b-11e9-8748-600c41cd4981.png)

_Originally posted by @zhangtibin in https://github.com/alibaba/coobjc/issues/2#issuecomment-468194137_

**Comment by NianJi** [comment]
Logically, there will be no impact, but in order to avoid confusion,  I will fix it.
