### ISSUE TITLE
COCoroutine 源码 有一处不太理解

### ISSUE THREAD

**Issue by DeanGuo** [alibaba/coobjc#83]
COCoroutine *coObj = [[self alloc] initWithBlock:block onQueue:queue];
coObj.queue = queue;
实例化的时候 已经给 .queue 赋值了
为什么还要再单独赋值一次呢 ？

**Comment by youzige** [comment]
安全编码，为了避免开发人员在init方法中忘记赋值导致异常

**Comment by NianJi** [comment]
你看的什么时候的代码呢？我搜了下已经没有这个代码啊

**Comment by DeanGuo** [comment]
三月份的代码，现在目录结构都变了当时path是core，现在是co，我看了一下最新的代码确实没有这个逻辑了。
