### ISSUE TITLE
关于chan_alt中value的疑问

### ISSUE THREAD

**Issue by JQShowtime** [alibaba/coobjc#88]
阅读源码时有一个小疑问，希望大神能解答！

在send_nonblock:方法实现中有：
`int8_t v = 1;`
`channbsend_custom_exec(_chan, &v, custom_exec);`

在receiveWithOnCancel:方法实现中有：
`uint8_t val = 0;`
`int ret = chanrecv_custom_exec(_chan, &val, cancel_exec);`

而在altexec()方法中有调用
`altcopy(a, other)`
copy的即是chan_alt中value。

想问一下这个value代表的是什么意义？
另外问一下chan_alt翻译成中文是什么？我只能想到是实体一类的意思，但是感觉不准确

**Comment by NianJi** [comment]
chan_alt 可以理解为任务，是一次send或者receive的任务的数据结构。

value就是要传递的值。 altcopy可以理解为将send任务中的值拷贝到receive任务中，这样就完成了发送接收的过程。 只不过 COChan 的oc实现里面没有用到值，所以随便传了一个 int8。
